# Generated by Django 5.0 on 2024-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_product_additional_info_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_info',
            name='detail',
            field=models.CharField(default='SOME', max_length=100),
        ),
    ]
