# Generated by Django 5.0 on 2024-02-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_additional_info_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='detail',
            field=models.CharField(max_length=100),
        ),
    ]
