# Generated by Django 5.0 on 2024-02-10 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_product_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
