# Generated by Django 5.0 on 2024-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_product_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='detail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='specification',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
