# Generated by Django 5.0 on 2024-02-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
